
package shapes.panels;

import canva.Canva;
import shapes.controls.PointsMoveControl;
import shapes.shapes.BresenhamLine;
import utils.Utils;

import javax.swing.table.AbstractTableModel;
import java.awt.*;

/**
 * @author	Gomon Sergey
 * 
 * Класс панели управления для графического объекта BresenhamLine
 * 
 * @see BresenhamLine
 */
public class BresenhamLinePanel extends AbstractGraphicsObjectPanel {

	BresenhamLine bresenhamLine;
	Canva canva;
	
    public BresenhamLinePanel(BresenhamLine bresenhamLine, Canva canva) {
		initComponents();
		pointMoveButton.setIcon(Utils.getIcon("point_move", 25, 25));
		pointMoveButton.setToolTipText("Перемещение точек");
		pointMoveButton.setFocusable(false);		
		this.bresenhamLine = bresenhamLine;
		this.canva = canva;
		setPreferredSize(new Dimension(250,0));
		setMinimumSize(new Dimension(200,0));
		updatePanel();
    }

	@Override
    public final void updatePanel() {
		if(bresenhamLine.isDirectLine()) {
			
			String[] columnNames = {"№", "(x,y)"};
			Object[][] data = new Object[bresenhamLine.getPointsCount()][2];			
			
			for(int i = 0; i < bresenhamLine.getPointsCount(); i++) {
				data[i][0] = (i+1) + ".";
				data[i][1] = "(" + bresenhamLine.getX().get(i) + ", " +
						bresenhamLine.getY().get(i) + ")";
			}
			
			resultTable.setModel(new javax.swing.table.DefaultTableModel(
					data, columnNames));			
		} else {
			
			String[] columnNames = {"№", "(x,y)", 
				"err", "plot(x,y)"};
			Object[][] data = new Object[bresenhamLine.getInfoListSize()][4];
			
			for(int i = 0; i < bresenhamLine.getInfoListSize(); i++) {
				data[i][0] = (i+1) + ".";
				data[i][1] = "(" + bresenhamLine.getRealXList().get(i) + "," +
						bresenhamLine.getRealYList().get(i) + ")";
				data[i][2] = bresenhamLine.getErrorsList().get(i);
				
				if(bresenhamLine.getPlottedXList().get(i) < 0 
						|| bresenhamLine.getPlottedYList().get(i) < 0) {
					data[i][3] = "---";
				} else {
					data[i][3] = "(" + bresenhamLine.getPlottedXList().get(i) + 
							", " + bresenhamLine.getPlottedYList().get(i) + ")";
				}
				
			}
			
			resultTable.setModel(new javax.swing.table.DefaultTableModel(
					data, columnNames));
		}
	
        //Обновляем графическое представление таблицы
        ((AbstractTableModel) resultTable.getModel()).fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pointMoveButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(180, 241));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Действия"));

        pointMoveButton.setMaximumSize(new java.awt.Dimension(26, 26));
        pointMoveButton.setMinimumSize(new java.awt.Dimension(26, 26));
        pointMoveButton.setPreferredSize(new java.awt.Dimension(26, 26));
        pointMoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointMoveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pointMoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pointMoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Точки"));

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(resultTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

	private void pointMoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointMoveButtonActionPerformed
		canva.setGraphicsObjectControl(new PointsMoveControl(bresenhamLine));
	}//GEN-LAST:event_pointMoveButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pointMoveButton;
    private javax.swing.JTable resultTable;
    // End of variables declaration//GEN-END:variables


}
