/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PolygonPanel.java
 *
 * Created on Nov 18, 2011, 11:40:32 AM
 */
package shapes.panels;

import canva.Canva;
import shapes.controls.AffineControl;
import shapes.controls.PointsMoveControl;
import shapes.shapes.Polygon;
import utils.Utils;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.AbstractTableModel;
import java.text.DecimalFormat;
import shapes.controls.CohenSutherlandControl;
import shapes.controls.CyrusBeckControl;

/**
 *
 * @author Sergey
 */
public class PolygonPanel extends AbstractGraphicsObjectPanel {

	private Canva canva;
	private Polygon shape;
	
	/** Creates new form PolygonPanel */
	public PolygonPanel(Polygon shape, final Canva canva) {
		initComponents();
		this.shape = shape;
		this.canva = canva;
		
		pointMoveButton.setIcon(Utils.getIcon("point_move", 25, 25));
		pointMoveButton.setToolTipText("Перемещение точек");
		pointMoveButton.setFocusable(false);	
		
		affineButton.setIcon(Utils.getIcon("affine_transform_2d", 25, 25));
		affineButton.setToolTipText("Аффинные преобразования");
		affineButton.setFocusable(false);			
		
		cirusBackButton.setIcon(Utils.getIcon("cyrus-beck", 25, 25));
		cirusBackButton.setToolTipText("Отсечение методом Кируса-Бека");
		cirusBackButton.setFocusable(false);			
		
		cohenSutherlandButton.setIcon(Utils.getIcon("cohen-sutherland", 25, 25));
		cohenSutherlandButton.setToolTipText("Отсечение методом Коена-Сазерленда");
		cohenSutherlandButton.setFocusable(false);		
		
		ChangeListener cangeListener = new ChangeListener() {
			@Override
			public void stateChanged(ChangeEvent e) {
				canva.repaintCanva();
			}
		};		
		
		antialiasingCheckBox.addChangeListener(cangeListener);
		
		updatePanel();			
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pointMoveButton = new javax.swing.JButton();
        affineButton = new javax.swing.JButton();
        cirusBackButton = new javax.swing.JButton();
        cohenSutherlandButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        antialiasingCheckBox = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        matrixTable = new javax.swing.JTable();
        resetButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(250, 32767));
        setMinimumSize(new java.awt.Dimension(250, 0));
        setPreferredSize(new java.awt.Dimension(250, 300));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Действия")));

        pointMoveButton.setMaximumSize(new java.awt.Dimension(26, 26));
        pointMoveButton.setMinimumSize(new java.awt.Dimension(26, 26));
        pointMoveButton.setPreferredSize(new java.awt.Dimension(26, 26));
        pointMoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointMoveButtonActionPerformed(evt);
            }
        });

        affineButton.setToolTipText("");
        affineButton.setMaximumSize(new java.awt.Dimension(26, 26));
        affineButton.setMinimumSize(new java.awt.Dimension(26, 26));
        affineButton.setPreferredSize(new java.awt.Dimension(26, 26));
        affineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affineButtonActionPerformed(evt);
            }
        });

        cirusBackButton.setPreferredSize(new java.awt.Dimension(26, 26));
        cirusBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cirusBackButtonActionPerformed(evt);
            }
        });

        cohenSutherlandButton.setToolTipText("");
        cohenSutherlandButton.setPreferredSize(new java.awt.Dimension(26, 26));
        cohenSutherlandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cohenSutherlandButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pointMoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(affineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cirusBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cohenSutherlandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pointMoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(affineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cirusBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cohenSutherlandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Настройки"));

        antialiasingCheckBox.setText("Сглаживание");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(antialiasingCheckBox)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(antialiasingCheckBox)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Матрица преобразований"));

        matrixTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(matrixTable);

        resetButton.setText("Сброс");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(resetButton)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

	private void pointMoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointMoveButtonActionPerformed
		canva.setGraphicsObjectControl(new PointsMoveControl(shape));
	}//GEN-LAST:event_pointMoveButtonActionPerformed

	private void affineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affineButtonActionPerformed
		canva.setGraphicsObjectControl(new AffineControl(shape));
	}//GEN-LAST:event_affineButtonActionPerformed

	private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
		shape.applyAffine(shape.affineMatrix.inverse());
		canva.resetGraphicsObjectControl();
	}//GEN-LAST:event_resetButtonActionPerformed

	private void cirusBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cirusBackButtonActionPerformed
		canva.setGraphicsObjectControl(new CyrusBeckControl(shape));
	}//GEN-LAST:event_cirusBackButtonActionPerformed

	private void cohenSutherlandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cohenSutherlandButtonActionPerformed
		canva.setGraphicsObjectControl(new CohenSutherlandControl(shape));
	}//GEN-LAST:event_cohenSutherlandButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton affineButton;
    private javax.swing.JCheckBox antialiasingCheckBox;
    private javax.swing.JButton cirusBackButton;
    private javax.swing.JButton cohenSutherlandButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable matrixTable;
    private javax.swing.JButton pointMoveButton;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables

	@Override
	public final void updatePanel() {
		if(shape.isComplete()) {
			pointMoveButton.setEnabled(true);
			affineButton.setEnabled(true);
			cirusBackButton.setEnabled(true);
			cohenSutherlandButton.setEnabled(true);
		} else {
			pointMoveButton.setEnabled(false);
			affineButton.setEnabled(false);
			cirusBackButton.setEnabled(false);
			cohenSutherlandButton.setEnabled(false);
		}

		shape.setAntialiasing(antialiasingCheckBox.isSelected());
		
		String[] columnNames = new String[] {" ", " ", " "};
		Object[][] data = new Object[3][3];

		DecimalFormat myFormatter = new DecimalFormat("######.##");
		
		if(shape.affineMatrix == null) {
			for(int i = 0; i < 3; i++) {
				if(i == 0) {
					data[i][0] = 1;
				} else {
					data[i][0] = 0;
				}
				if(i == 1) {
					data[i][1] = 1;
				} else {
					data[i][1] = 0;
				}
				if(i == 2) {
					data[i][2] = 1;
				} else {
					data[i][2] = 0;
				}
			}		
		} else {
			for(int i = 0; i < 3; i++) {
				data[i][0] = myFormatter.format(shape.affineMatrix.get(i, 0));
				data[i][1] = myFormatter.format(shape.affineMatrix.get(i, 1));
				data[i][2] = myFormatter.format(shape.affineMatrix.get(i, 2));
			}
		}

		matrixTable.setModel(new javax.swing.table.DefaultTableModel(
				data, columnNames));

		//Обновляем графическое представление таблицы
		((AbstractTableModel) matrixTable.getModel()).fireTableDataChanged();
	}
}
